[2021-05-30 19:26:48,120] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: data_engineering_assignment_2.Load_python_libraries 2021-05-28T00:00:00+00:00 [queued]>
[2021-05-30 19:26:48,181] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: data_engineering_assignment_2.Load_python_libraries 2021-05-28T00:00:00+00:00 [queued]>
[2021-05-30 19:26:48,183] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-30 19:26:48,184] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-30 19:26:48,185] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-30 19:26:48,206] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): Load_python_libraries> on 2021-05-28T00:00:00+00:00
[2021-05-30 19:26:48,232] {standard_task_runner.py:52} INFO - Started process 47 to run task
[2021-05-30 19:26:48,250] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_engineering_assignment_2', 'Load_python_libraries', '2021-05-28T00:00:00+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment_2_dags.py', '--cfg-path', '/tmp/tmpxbrnk5db', '--error-file', '/tmp/tmp6e5h1nkw']
[2021-05-30 19:26:48,263] {standard_task_runner.py:77} INFO - Job 17: Subtask Load_python_libraries
[2021-05-30 19:26:48,400] {logging_mixin.py:104} INFO - Running <TaskInstance: data_engineering_assignment_2.Load_python_libraries 2021-05-28T00:00:00+00:00 [running]> on host d1b2a4d53792
[2021-05-30 19:26:48,532] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mohannad alsouqi
AIRFLOW_CTX_DAG_ID=data_engineering_assignment_2
AIRFLOW_CTX_TASK_ID=Load_python_libraries
AIRFLOW_CTX_EXECUTION_DATE=2021-05-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-28T00:00:00+00:00
[2021-05-30 19:26:48,537] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-30 19:26:48,543] {bash.py:158} INFO - Running command: pip install sqlalchemy matplotlib sklearn
[2021-05-30 19:26:48,598] {bash.py:169} INFO - Output:
[2021-05-30 19:26:50,051] {bash.py:173} INFO - WARNING: The directory '/home/airflow/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
[2021-05-30 19:26:50,438] {bash.py:173} INFO - Requirement already satisfied: sqlalchemy in /home/airflow/.local/lib/python3.6/site-packages (1.3.24)
[2021-05-30 19:26:50,510] {bash.py:173} INFO - Requirement already satisfied: matplotlib in /home/airflow/.local/lib/python3.6/site-packages (3.3.4)
[2021-05-30 19:26:50,532] {bash.py:173} INFO - Requirement already satisfied: sklearn in /home/airflow/.local/lib/python3.6/site-packages (0.0)
[2021-05-30 19:26:50,538] {bash.py:173} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/airflow/.local/lib/python3.6/site-packages (from matplotlib) (1.3.1)
[2021-05-30 19:26:50,549] {bash.py:173} INFO - Requirement already satisfied: cycler>=0.10 in /home/airflow/.local/lib/python3.6/site-packages (from matplotlib) (0.10.0)
[2021-05-30 19:26:50,556] {bash.py:173} INFO - Requirement already satisfied: numpy>=1.15 in /home/airflow/.local/lib/python3.6/site-packages (from matplotlib) (1.19.5)
[2021-05-30 19:26:50,561] {bash.py:173} INFO - Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/airflow/.local/lib/python3.6/site-packages (from matplotlib) (2.4.7)
[2021-05-30 19:26:50,572] {bash.py:173} INFO - Requirement already satisfied: python-dateutil>=2.1 in /home/airflow/.local/lib/python3.6/site-packages (from matplotlib) (2.8.1)
[2021-05-30 19:26:50,586] {bash.py:173} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/airflow/.local/lib/python3.6/site-packages (from matplotlib) (8.2.0)
[2021-05-30 19:26:50,596] {bash.py:173} INFO - Requirement already satisfied: scikit-learn in /home/airflow/.local/lib/python3.6/site-packages (from sklearn) (0.24.2)
[2021-05-30 19:26:50,722] {bash.py:173} INFO - Requirement already satisfied: six in /home/airflow/.local/lib/python3.6/site-packages (from cycler>=0.10->matplotlib) (1.15.0)
[2021-05-30 19:26:50,731] {bash.py:173} INFO - Requirement already satisfied: joblib>=0.11 in /home/airflow/.local/lib/python3.6/site-packages (from scikit-learn->sklearn) (1.0.1)
[2021-05-30 19:26:50,744] {bash.py:173} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/airflow/.local/lib/python3.6/site-packages (from scikit-learn->sklearn) (2.1.0)
[2021-05-30 19:26:50,754] {bash.py:173} INFO - Requirement already satisfied: scipy>=0.19.1 in /home/airflow/.local/lib/python3.6/site-packages (from scikit-learn->sklearn) (1.5.4)
[2021-05-30 19:27:11,150] {bash.py:173} INFO - WARNING: You are using pip version 20.2.4; however, version 21.1.2 is available.
[2021-05-30 19:27:11,151] {bash.py:173} INFO - You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[2021-05-30 19:27:11,409] {bash.py:177} INFO - Command exited with return code 0
[2021-05-30 19:27:11,477] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=data_engineering_assignment_2, task_id=Load_python_libraries, execution_date=20210528T000000, start_date=20210530T192648, end_date=20210530T192711
[2021-05-30 19:27:11,553] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-30 19:27:11,580] {local_task_job.py:146} INFO - Task exited with return code 0
